export const GET_ENTRANCES = 'GET_ENTRANCES'
export const GET_ENTRANCES_BY_FIELD = 'GET_ENTRANCES_BY_FIELD'
export const GET_ENTRANCES_SUCCESS = 'GET_ENTRANCES_SUCCESS'
export const GET_ENTRANCES_ERROR = 'GET_ENTRANCES_ERROR'

export const ADD_ENTRANCE = 'ADD_ENTRANCE'
export const ADD_ENTRANCE_SUCCESS = 'ADD_ENTRANCE_SUCCESS'
export const ADD_ENTRANCE_ERROR = 'ADD_ENTRANCE_ERROR'

export const EDIT_ENTRANCE = 'EDIT_ENTRANCE'
export const EDIT_ENTRANCE_SUCCESS = 'EDIT_ENTRANCE_SUCCESS'

export const DELETE_ENTRANCE = 'DELETE_ENTRANCE'
export const DELETE_ENTRANCE_SUCCESS = 'DELETE_ENTRANCE_SUCCESS'

export const GET_ENTRANCESPAGE = 'GET_ENTRANCESPAGE'
export const GET_ENTRANCESPAGE_SUCCESS = 'GET_ENTRANCESPAGE_SUCCESS'
export const GET_ENTRANCESPAGE_ERROR = 'GET_ENTRANCESPAGE_ERROR'
