export const GET_SUPPLIERS = 'GET_SUPPLIERS'
export const GET_SUPPLIERS_BY_FIELD = 'GET_SUPPLIERS_BY_FIELD'
export const GET_SUPPLIERS_SUCCESS = 'GET_SUPPLIERS_SUCCESS'

export const ADD_SUPPLIER = 'ADD_SUPPLIER'
export const ADD_SUPPLIER_SUCCESS = 'ADD_SUPPLIER_SUCCESS'
export const ADD_SUPPLIER_ERROR = 'ADD_SUPPLIER_ERROR'

export const EDIT_SUPPLIER = 'EDIT_SUPPLIER'
export const EDIT_SUPPLIER_SUCCESS = 'EDIT_SUPPLIER_SUCCESS'

export const DELETE_SUPPLIER = 'DELETE_SUPPLIER'
export const DELETE_SUPPLIER_SUCCESS = 'DELETE_SUPPLIER_SUCCESS'

export const GET_SUPPLIERSPAGE = 'GET_SUPPLIERSPAGE'
export const GET_SUPPLIERSPAGE_SUCCESS = 'GET_SUPPLIERSPAGE_SUCCESS'
export const GET_SUPPLIERSPAGE_ERROR = 'GET_SUPPLIERSPAGE_ERROR'
