export const GET_CLIENTS = 'GET_CLIENTS'
export const GET_CLIENTS_BY_FIELD = 'GET_CLIENTS_BY_FIELD'
export const GET_CLIENTS_SUCCESS = 'GET_CLIENTS_SUCCESS'

export const ADD_CLIENT = 'ADD_CLIENT'
export const ADD_CLIENT_SUCCESS = 'ADD_CLIENT_SUCCESS'
export const ADD_CLIENT_ERROR = 'ADD_CLIENT_ERROR'

export const EDIT_CLIENT = 'EDIT_CLIENT'
export const EDIT_CLIENT_SUCCESS = 'EDIT_CLIENT_SUCCESS'

export const DELETE_CLIENT = 'DELETE_CLIENT'
export const DELETE_CLIENT_SUCCESS = 'DELETE_CLIENT_SUCCESS'

