export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const GET_PRODUCTS_BY_FIELD = 'GET_PRODUCTS_BY_FIELD'
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS'

export const ADD_PRODUCT = 'ADD_PRODUCT'
export const ADD_PRODUCT_SUCCESS = 'ADD_PRODUCT_SUCCESS'
export const ADD_PRODUCT_ERROR = 'ADD_PRODUCT_ERROR'

export const EDIT_PRODUCT = 'EDIT_PRODUCT'
export const EDIT_PRODUCT_SUCCESS = 'EDIT_PRODUCT_SUCCESS'

export const ADD_CATEGORY = 'ADD_CATEGORY'
export const ADD_CATEGORY_SUCCESS = 'ADD_CATEGORY_SUCCESS'

export const DELETE_PRODUCT = 'DELETE_PRODUCT'
export const DELETE_PRODUCT_SUCCESS = 'DELETE_PRODUCT_SUCCESS'

export const GET_PRODUCTSPAGE = 'GET_PRODUCTSPAGE'
export const GET_PRODUCTSPAGE_SUCCESS = 'GET_PRODUCTSPAGE_SUCCESS'
export const GET_PRODUCTSPAGE_ERROR = 'GET_PRODUCTSPAGE_ERROR'
