export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORIES_SUCCESS = 'GET_CATEGORIES_SUCCESS'

export const GET_PRODUCTSPAGE = 'GET_PRODUCTSPAGE'
export const GET_PRODUCTSPAGE_SUCCESS = 'GET_PRODUCTSPAGE_SUCCESS'
export const GET_PRODUCTSPAGE_ERROR = 'GET_PRODUCTSPAGE_ERROR'
