export const GET_TAKEOFFS = 'GET_TAKEOFFS'
export const GET_TAKEOFFS_BY_FIELD = 'GET_TAKEOFFS_BY_FIELD'
export const GET_TAKEOFFS_SUCCESS = 'GET_TAKEOFFS_SUCCESS'
export const GET_TAKEOFFS_ERROR = 'GET_TAKEOFFS_ERROR'

export const ADD_TAKEOFF = 'ADD_TAKEOFF'
export const ADD_TAKEOFF_SUCCESS = 'ADD_TAKEOFF_SUCCESS'
export const ADD_TAKEOFF_ERROR = 'ADD_TAKEOFF_ERROR'

export const EDIT_TAKEOFF = 'EDIT_TAKEOFF'
export const EDIT_TAKEOFF_SUCCESS = 'EDIT_TAKEOFF_SUCCESS'

export const DELETE_TAKEOFF = 'DELETE_TAKEOFF'
export const DELETE_TAKEOFF_SUCCESS = 'DELETE_TAKEOFF_SUCCESS'

export const GET_TAKEOFFSPAGE = 'GET_TAKEOFFSPAGE'
export const GET_TAKEOFFSPAGE_SUCCESS = 'GET_TAKEOFFSPAGE_SUCCESS'
export const GET_TAKEOFFSPAGE_ERROR = 'GET_TAKEOFFSPAGE_ERROR'
